/**
 * Created on 2025/8/14
 */
package webrtc_cj


public class RTCRtpReceiver <: WebrtcClass {

    public init(id: Int64) {
        super(id, this)
    }

//    public func getParameters(): RTCRtpReceiveParameters {
//
//    }
//    public func getStats(): Promise<RTCStatsReport> {
//
//    }
//
//    public func getContributingSources(): Array<RTCRtpContributingSource> {
//
//    }
//
//    public func getSynchronizationSources(): Array<RTCRtpSynchronizationSource> {
//
//    }

}

